replicaCount: 1

image:
  repository: nginx
  tag: "1.25-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  listenPorts: '[{"HTTP":80}]'
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: Prefix
